development:
  adapter: postgresql
  encoding: unicode
  database: quote_fetcher_dev
  host: localhost
  pool: 5
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: quote_fetcher_test
  host: localhost
  pool: 5
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>