development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  PLAYUP_URL: https://play.playup.com/lobby?modal=signin
  PLAYUP_USERNAME: sharat94@hotmail.com
  PLAYUP_PASSWORD: sharan123
  SIDEKIQ_USERNAME: sharat94
  SIDEKIQ_PASSWORD: sharan123

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  PLAYUP_URL: https://play.playup.com/lobby?modal=signin
  PLAYUP_USERNAME: sharat94@hotmail.com
  PLAYUP_PASSWORD: sharan123
  SIDEKIQ_USERNAME: sharat94
  SIDEKIQ_PASSWORD: sharan123